// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// robustweights
NumericVector robustweights(NumericMatrix X, double delta, double zeta);
RcppExport SEXP _Rcvxclustr_robustweights(SEXP XSEXP, SEXP deltaSEXP, SEXP zetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type zeta(zetaSEXP);
    rcpp_result_gen = Rcpp::wrap(robustweights(X, delta, zeta));
    return rcpp_result_gen;
END_RCPP
}
// robust_convex_cluster
List robust_convex_cluster(NumericMatrix X, NumericMatrix W, NumericMatrix V, NumericMatrix Y, NumericMatrix Z, NumericMatrix E, int max_iter, double tol_abs, double lambda, double rho, double tau, NumericVector wt);
RcppExport SEXP _Rcvxclustr_robust_convex_cluster(SEXP XSEXP, SEXP WSEXP, SEXP VSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP ESEXP, SEXP max_iterSEXP, SEXP tol_absSEXP, SEXP lambdaSEXP, SEXP rhoSEXP, SEXP tauSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type E(ESEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol_abs(tol_absSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wt(wtSEXP);
    rcpp_result_gen = Rcpp::wrap(robust_convex_cluster(X, W, V, Y, Z, E, max_iter, tol_abs, lambda, rho, tau, wt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rcvxclustr_robustweights", (DL_FUNC) &_Rcvxclustr_robustweights, 3},
    {"_Rcvxclustr_robust_convex_cluster", (DL_FUNC) &_Rcvxclustr_robust_convex_cluster, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rcvxclustr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
