# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

robustweights <- function(X, delta = 15.0, zeta = 0.1) {
    .Call('_Rcvxclustr_robustweights', PACKAGE = 'Rcvxclustr', X, delta, zeta)
}

robust_convex_cluster <- function(X, W, V, Y, Z, E, max_iter, tol_abs, lambda, rho, tau, wt) {
    .Call('_Rcvxclustr_robust_convex_cluster', PACKAGE = 'Rcvxclustr', X, W, V, Y, Z, E, max_iter, tol_abs, lambda, rho, tau, wt)
}

